import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthContext from "@/AuthContext";
import Link from "next/link";
// import { useContext } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossOrigin=""/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
              <div style={{ padding: '0 2em', 'display': 'flex', 'gap': '1em', }}>
                <div><Link href="/map">Map View</Link></div>
                <div><Link href="/login">Sign up or Login</Link></div>
              </div>
              <div style={{ padding: '2em' }}>
                {children}
              </div>
            </div>
      </body>
    </html>
  );
}
